<?xml version="1.0"?>
<robot name="rosbot" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Properties -->
  <xacro:property name="M_PI" value="3.14159"/>
  <!-- Base Size -->
  <xacro:property name="base_length" value="0.184" />
  <xacro:property name="base_width" value="0.120" />
  <xacro:property name="base_height" value="0.068" />

  <!-- Wheel Properties -->
  <xacro:property name="wheel_base" value="0.123" />
  <xacro:property name="wheel_track" value="0.146" />
  <xacro:property name="wheel_vertical_offset" value="0" />
  <xacro:property name="wheel_width" value="0.025" />
  <xacro:property name="wheel_radius" value="0.040" />

  <!-- Calculated Properties -->
  <xacro:property name="base_vertical_offset" value="${wheel_radius-wheel_vertical_offset}" />

  <!-- Materials -->
  <material name="Blue">
    <color rgba="0.0 0.0 0.8 1.0"/>
  </material>
  <material name="Grey">
    <color rgba="0.7 0.7 0.7 1.0"/>
  </material>

  <!-- Wheel macro definition -->
  <xacro:macro name="rosbot_wheel" params="wheel_prefix flip *joint_pose">
    <!-- Wheel link -->
    <link name="${wheel_prefix}_wheel_link">
      <visual>
        <origin xyz="${flip*wheel_radius} ${-flip*wheel_width/2} ${-wheel_radius}" rpy="${M_PI/2} 0 ${flip*M_PI/2+M_PI/2}" />
        <geometry>
          <mesh filename="package://rosbot_description/meshes/wheel.dae" />
        </geometry>
        <material name="Grey" />
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}" />
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0"/>
        <mass value="0.15" />
        <inertia  ixx="0.0001" ixy="0" ixz="0"
                  iyy="0.0001" iyz="0"
                  izz="0.0001" />
      </inertial>
    </link>

    <gazebo reference="${wheel_prefix}_wheel_link">
      <mu1 value="200.0"/>
      <mu2 value="100.0"/>
      <kp value="10000000.0" />
      <kd value="1.0" />
      <material>Gazebo/Grey</material>
    </gazebo>

    <!-- Wheel to base joint -->
    <joint name="${wheel_prefix}" type="continuous">
      <parent link="base_link"/>
      <child link="${wheel_prefix}_wheel_link"/>
      <xacro:insert_block name="joint_pose"/>
      <axis xyz="0 1 0" rpy="0 0 0" />
    </joint>
  </xacro:macro>

  <!-- Base footprint link -->
  <link name="base_footprint"/>

  <!-- Footprint to base joint -->
  <joint name="footprint_joint" type="fixed">
    <origin xyz="0 0 ${base_vertical_offset}" rpy="0 0 0" />
    <parent link="base_footprint" />
    <child link="base_link" />
  </joint>

  <!-- Base link -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://rosbot_description/meshes/base.dae"/>
      </geometry>
      <material name="Blue" />
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.857" />
      <inertia  ixx="2.17" ixy="0" ixz="0"
                iyy="3.09" iyz="0"
                izz="4.76" />
    </inertial>
  </link>

  <gazebo reference="base_link">
    <material>Gazebo/Blue</material>
  </gazebo>

  <!-- Create wheels from macro -->
  <xacro:rosbot_wheel wheel_prefix="front_left" flip="-1">
    <origin xyz="${wheel_base/2} ${wheel_track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:rosbot_wheel>
  <xacro:rosbot_wheel wheel_prefix="front_right" flip="1">
    <origin xyz="${wheel_base/2} ${-wheel_track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:rosbot_wheel>
  <xacro:rosbot_wheel wheel_prefix="rear_left" flip="-1">
    <origin xyz="${-wheel_base/2} ${wheel_track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:rosbot_wheel>
  <xacro:rosbot_wheel wheel_prefix="rear_right" flip="1">
    <origin xyz="${-wheel_base/2} ${-wheel_track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:rosbot_wheel>

  <!-- ROS2 Control -->
  <ros2_control name="GazeboSystem" type="system">
    <!-- ROS 2 Humble -->
    <hardware>
      <plugin>ign_ros2_control/IgnitionSystem</plugin>
    </hardware>


    <!-- Front wheels (for steering) -->
    <joint name="front_left">
      <command_interface name="velocity">
        <param name="min">-10</param>
        <param name="max">10</param>
      </command_interface>
      <state_interface name="position" />
      <state_interface name="velocity" />
    </joint>

    <joint name="front_right">
      <command_interface name="velocity">
        <param name="min">-10</param>
        <param name="max">10</param>
      </command_interface>
      <state_interface name="position" />
      <state_interface name="velocity" />
    </joint>

    <!-- Rear wheels (for driving) -->
    <joint name="rear_left">
      <command_interface name="velocity">
        <param name="min">-10</param>
        <param name="max">10</param>
      </command_interface>
      <state_interface name="position" />
      <state_interface name="velocity" />
    </joint>

    <joint name="rear_right">
      <command_interface name="velocity">
        <param name="min">-10</param>
        <param name="max">10</param>
      </command_interface>
      <state_interface name="position" />
      <state_interface name="velocity" />
    </joint>
  </ros2_control>

  <gazebo>
    <!-- ROS 2 Humble -->
    <plugin filename="ign_ros2_control-system" name="ign_ros2_control::IgnitionROS2ControlPlugin">
      <parameters>$(find rosbot_control)/config/control.yaml</parameters>
    </plugin>

  </gazebo>

</robot>